[package]
name = "rfs"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = { version = "7.1.3", features = ["docsrs"] }
quinn = "0.11.3"
rustls-pemfile = "2.1.3"
tokio = { version = "1.39.3", features = [
    "rt-multi-thread",
    "net",
    "fs",
    "macros",
] }
tokio-rustls = "0.26.0"
